<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
	*{font-family:DejaVu Sans, sans-serif}
	body{color:#1f2937;font-size:11px;margin:0}
	.head{border-bottom:2px solid #2563eb;padding-bottom:10px;margin-bottom:12px}
	.head h1{margin:0 0 2px;font-size:18px;color:#1e3a8a}
	.head .muted{color:#6b7280;font-size:11px}
	.meta{margin:8px 0 12px;font-size:11px}
	.meta span{display:inline-block;margin-right:18px}
	.tiles{width:100%;margin-bottom:12px}
	.tiles td{padding:8px;background:#f3f6fc;border:1px solid #e5e9f2;text-align:center}
	.tiles .val{font-size:17px;font-weight:bold;color:#1e40af}
	.tiles .lbl{font-size:10px;color:#6b7280;text-transform:uppercase}
	table.data{width:100%;border-collapse:collapse}
	table.data th{background:#1e3a8a;color:#fff;padding:6px 8px;text-align:left;font-size:10px}
	table.data td{padding:5px 8px;border-bottom:1px solid #e5e7eb;font-size:10px}
	.foot{margin-top:14px;font-size:9px;color:#9ca3af;text-align:center}
</style>
</head>
<body>
	<div class="head">
		<h1>{{ $company->name ?? 'Company' }} — {{ $title }}</h1>
		<div class="muted">Employment Management Portal · {{ $subtitle }}</div>
	</div>

	<div class="meta">
		<span><b>Period:</b> {{ \Carbon\Carbon::parse($from)->format('m/d/Y') }} – {{ \Carbon\Carbon::parse($to)->format('m/d/Y') }}</span>
		<span><b>Office:</b> {{ $office->name ?? 'All Offices' }}</span>
		<span><b>Generated:</b> {{ now()->format('m/d/Y, h:i A') }}</span>
	</div>

	<table class="tiles">
		<tr>
			@foreach($tiles as $t)
			<td><div class="val">{{ $t['value'] }}</div><div class="lbl">{{ $t['label'] }}</div></td>
			@endforeach
		</tr>
	</table>

	<table class="data">
		<thead><tr>@foreach($headings as $h)<th>{{ $h }}</th>@endforeach</tr></thead>
		<tbody>
			@forelse($rows as $row)
			<tr>@foreach($headings as $h)<td>{{ $row[$h] }}</td>@endforeach</tr>
			@empty
			<tr><td colspan="{{ count($headings) }}" style="text-align:center;padding:16px;color:#9ca3af;">No records for this period.</td></tr>
			@endforelse
		</tbody>
	</table>

	<div class="foot">Generated by Employment Management Portal · {{ count($rows) }} rows</div>
</body>
</html>
