<?php

namespace App\Http\Controllers;

use App\Models\Office;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class OfficeController extends Controller
{
    protected function companyId(): int
    {
        return auth()->user()->company_id ?? Office::value('company_id');
    }

    public function index()
    {
        $offices = Office::withCount('employees')
            ->where('company_id', $this->companyId())->latest()->paginate(15);

        return view('offices.index', compact('offices'));
    }

    public function store(Request $request)
    {
        $data = $this->validateOffice($request);
        $data['company_id'] = $this->companyId();
        Office::create($data); // qr_secret auto-generated by model hook

        return back()->with('success', 'Office created with its own rotating-QR secret.');
    }

    public function update(Request $request, Office $office)
    {
        abort_unless($office->company_id === $this->companyId(), 403);
        $office->update($this->validateOffice($request));

        return back()->with('success', 'Office updated.');
    }

    public function destroy(Office $office)
    {
        abort_unless($office->company_id === $this->companyId(), 403);
        $office->delete();

        return back()->with('success', 'Office deleted.');
    }

    /** Rotate (reset) the office QR secret — invalidates all previously shown codes. */
    public function rotateSecret(Office $office)
    {
        abort_unless($office->company_id === $this->companyId(), 403);
        $office->update(['qr_secret' => Str::random(64)]);

        return back()->with('success', 'QR secret rotated — old codes are now invalid.');
    }

    protected function validateOffice(Request $request): array
    {
        return $request->validate([
            'name' => 'required|string|max:150',
            'code' => 'nullable|string|max:50',
            'address' => 'nullable|string',
            'city' => 'nullable|string|max:100',
            'work_start_time' => 'required|date_format:H:i',
            'work_end_time' => 'required|date_format:H:i',
            'late_grace_minutes' => 'required|integer|min:0|max:120',
            'is_active' => 'nullable|boolean',
        ]);
    }
}
