<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
	* { font-family: DejaVu Sans, sans-serif; }
	body { color: #1f2937; font-size: 11px; margin: 0; }
	.head { border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 14px; }
	.head h1 { margin: 0 0 2px; font-size: 18px; color: #1e3a8a; }
	.head .muted { color: #6b7280; font-size: 11px; }
	.meta { margin: 10px 0 14px; font-size: 11px; }
	.meta span { display: inline-block; margin-right: 18px; }
	.tiles { width: 100%; margin-bottom: 14px; }
	.tiles td { width: 25%; padding: 8px; background: #f3f6fc; border: 1px solid #e5e9f2; text-align: center; }
	.tiles .val { font-size: 18px; font-weight: bold; color: #1e40af; }
	.tiles .lbl { font-size: 10px; color: #6b7280; text-transform: uppercase; }
	table.data { width: 100%; border-collapse: collapse; }
	table.data th { background: #1e3a8a; color: #fff; padding: 6px 8px; text-align: left; font-size: 10px; }
	table.data td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; font-size: 10px; }
	.badge { padding: 1px 6px; border-radius: 4px; font-size: 9px; font-weight: bold; }
	.b-in { background: #dcfce7; color: #166534; }
	.b-out { background: #e5e7eb; color: #374151; }
	.b-late { background: #fef3c7; color: #92400e; }
	.b-ontime { background: #dcfce7; color: #166534; }
	.b-early { background: #e0e7ff; color: #3730a3; }
	.foot { margin-top: 16px; font-size: 9px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>
	<div class="head">
		<h1>{{ $company->name ?? 'Company' }} — Attendance Report</h1>
		<div class="muted">{{ config('app.name') }}</div>
	</div>

	<div class="meta">
		<span><b>Period:</b> {{ \Carbon\Carbon::parse($from)->format('m/d/Y') }} – {{ \Carbon\Carbon::parse($to)->format('m/d/Y') }}</span>
		<span><b>Office:</b> {{ $office->name ?? 'All Offices' }}</span>
		<span><b>Generated:</b> {{ now()->format('m/d/Y, h:i A') }}</span>
	</div>

	<table class="tiles">
		<tr>
			<td><div class="val">{{ $stats['total_scans'] }}</div><div class="lbl">Total Scans</div></td>
			<td><div class="val">{{ $stats['ontime'] }}</div><div class="lbl">On-time</div></td>
			<td><div class="val">{{ $stats['late'] }}</div><div class="lbl">Late</div></td>
			<td><div class="val">{{ $stats['days'] }}</div><div class="lbl">Days Covered</div></td>
		</tr>
	</table>

	<table class="data">
		<thead>
			<tr>
				<th>Employee</th><th>Code</th><th>Office</th><th>Type</th>
				<th>Status</th><th>Time</th><th>Date</th><th>Source</th><th>Location</th><th>IP</th>
			</tr>
		</thead>
		<tbody>
			@forelse($logs as $log)
			<tr>
				<td>{{ $log->employee->full_name ?? '—' }}</td>
				<td>{{ $log->employee->employee_code ?? '—' }}</td>
				<td>{{ $log->office->name ?? '—' }}</td>
				<td><span class="badge {{ $log->type=='in' ? 'b-in' : 'b-out' }}">{{ strtoupper($log->type) }}</span></td>
				<td>
					@php $sc = ['late'=>'b-late','ontime'=>'b-ontime','early_leave'=>'b-early'][$log->status] ?? 'b-out'; @endphp
					<span class="badge {{ $sc }}">{{ ucfirst(str_replace('_',' ',$log->status)) }}</span>
				</td>
				<td>{{ $log->scanned_at->format('h:i A') }}</td>
				<td>{{ $log->work_date->format('m/d/Y') }}</td>
				<td>{{ $log->source }}</td>
					<td>@if($log->latitude && $log->longitude)<a href="https://www.google.com/maps?q={{ $log->latitude }},{{ $log->longitude }}" style="color:#2563eb;text-decoration:none;">{{ $log->latitude }}, {{ $log->longitude }}</a>@else—@endif</td>
					<td>{{ $log->ip_address ?? '—' }}</td>
			</tr>
			@empty
			<tr><td colspan="10" style="text-align:center;padding:16px;color:#9ca3af;">No attendance records for this period.</td></tr>
			@endforelse
		</tbody>
	</table>

	<div class="foot">
		Generated by {{ config('app.name') }} · {{ $company->name ?? '' }} · {{ $logs->count() }} records
	</div>
</body>
</html>
